# Generated by Django 5.1.2 on 2024-11-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ai_analysis_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('success', models.BooleanField()),
                ('message', models.CharField(max_length=255)),
                ('cls', models.IntegerField()),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('request_timstamp', models.DateTimeField()),
                ('response_timestamp', models.DateTimeField()),
            ],
        ),
    ]
