# Generated by Django 5.1.2 on 2024-11-07 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ai_analysis_log',
            old_name='request_timstamp',
            new_name='request_timestamp',
        ),
    ]
