# Generated by Django 5.1.2 on 2024-11-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0002_rename_request_timstamp_ai_analysis_log_request_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_analysis_log',
            name='cls',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ai_analysis_log',
            name='confidence',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
    ]
