# Generated by Django 5.1.2 on 2024-11-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0003_alter_ai_analysis_log_cls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_analysis_log',
            name='cls',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ai_analysis_log',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
    ]
