# Generated by Django 5.1.2 on 2024-11-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0004_alter_ai_analysis_log_cls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_analysis_log',
            name='request_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ai_analysis_log',
            name='response_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
